import { Suspense } from "react";
import "./company-globals.css";
import { ConfigProvider } from "antd";
import SessionBridge from "./SessionBridge";
import CompanyStoreProvider from "@/redux/companyProvider";
import CompanyAuthGuard from "./CompanyAuthGuard";
import CompanySidebarShell from "./CompanySidebarShell";

export const metadata = {
  title: "SkillMedha Company Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CompanyStoreProvider>
      <ConfigProvider
        theme={{
          token: {
            fontSize: 16,
            colorPrimary: "#6BA8ED",
            colorPrimaryHover: "#1555b0",
            colorPrimaryActive: "#0f3e82",
            colorBorder: "#cbd5e0",
            controlHeight: 38,
            borderRadius: 8,
          },
          components: {
            Button: {
              controlHeight: 38,
              borderRadius: 8,
              fontWeight: 600,
            },
            Tooltip: {
              colorBgSpotlight: "#ffffff",
              colorTextLightSolid: "#6BA8ED",
            }
          }
        }}
      >
        {/* SessionBridge gets its own Suspense so it never blocks body mounting */}
        <Suspense fallback={null}>
          <SessionBridge />
        </Suspense>
        <CompanyAuthGuard>
          <CompanySidebarShell>
            {children}
          </CompanySidebarShell>
        </CompanyAuthGuard>
      </ConfigProvider>
    </CompanyStoreProvider>
  );
}
