import { Suspense } from "react";
import "./company-globals.css";
import { ConfigProvider } from "antd";
import SessionBridge from "./SessionBridge";
import CompanyStoreProvider from "@/redux/companyProvider";

export const metadata = {
  title: "SkillMedha Company Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CompanyStoreProvider>
      <ConfigProvider
        theme={{
          token: {
            fontSize: 16,
            colorPrimary: "#25A3A6",
            colorBorder: "#808080",
            colorPrimaryHover: "#1f8f92",
            controlHeight: 38,
          },
        }}
      >
        {/* SessionBridge gets its own Suspense so it never blocks body mounting */}
        <Suspense fallback={null}>
          <SessionBridge />
        </Suspense>
        {children}
      </ConfigProvider>
    </CompanyStoreProvider>
  );
}
