export const _10thSSC = [
  "CBSE",
  "ICSE",
  "CISCE",
  "NIOS",
  "Andhra Pradesh -Board of Secondary Education, Andhra Pradesh (BSEAP)",
  "Arunachal Pradesh -Directorate of School Education, Arunachal Pradesh",
  "Assam -Board of Secondary Education, Assam (SEBA)",
  "Bihar -Bihar School Examination Board (BSEB)",
  "Chhattisgarh -Chhattisgarh Board of Secondary Education (CGBSE)",
  "Goa -Goa Board of Secondary and Higher Secondary Education (GBSHSE)",
  "Gujarat -Gujarat Secondary and Higher Secondary Education Board (GSEB)",
  "Haryana -Board of School Education Haryana (HBSE)",
  "Himachal Pradesh -Himachal Pradesh Board of School Education (HPBOSE)",
  "Jharkhand -Jharkhand Academic Council (JAC)",
  "Karnataka -Karnataka Secondary Education Examination Board (KSEEB)",
  "Kerala -Kerala Board of Public Examinations (KBPE)",
  "Madhya Pradesh -Board of Secondary Education, Madhya Pradesh (MPBSE)",
  "Maharashtra -Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)",
  "Manipur -Board of Secondary Education, Manipur (BSEM)",
  "Meghalaya -Meghalaya Board of School Education (MBOSE)",
  "Mizoram -Mizoram Board of School Education (MBSE)",
  "Nagaland -Nagaland Board of School Education (NBSE)",
  "National -Central Board of Secondary Education (CBSE)",
  "National -Council for the Indian School Certificate Examinations (CISCE)",
  "National -National Institute of Open Schooling (NIOS)",
  "Odisha -Board of Secondary Education, Odisha (BSE Odisha)",
  "Punjab -Punjab School Education Board (PSEB)",
  "Rajasthan -Board of Secondary Education, Rajasthan (RBSE)",
  "Sikkim -Board of Secondary Education Sikkim",
  "Tamil Nadu -Tamil Nadu State Board of Secondary Education (TNBSE)",
  "Telangana -Board of Secondary Education, Telangana (BSE Telangana)",
  "Tripura -Tripura Board of Secondary Education (TBSE)",
  "Uttar Pradesh -Uttar Pradesh Madhyamik Shiksha Parishad (UPMSP)",
  "Uttarakhand -Uttarakhand Board of School Education (UBSE)",
  "West Bengal -West Bengal Board of Secondary Education (WBBSE)",
];

export const _12th_Boards = [
  "CBSE",
  "ICSE",
  "CISCE",
  "NIOS",
  "Andhra Pradesh-Board of Intermediate Education, Andhra Pradesh (BIEAP)",
  "Arunachal Pradesh-Directorate of School Education, Arunachal Pradesh",
  "Assam-Assam Higher Secondary Education Council (AHSEC)",
  "Bihar-Bihar School Examination Board (BSEB)",
  "Chhattisgarh-Chhattisgarh Board of Secondary Education (CGBSE)",
  "Goa-Goa Board of Secondary and Higher Secondary Education (GBSHSE)",
  "Gujarat-Gujarat Secondary and Higher Secondary Education Board (GSEB)",
  "Haryana-Board of School Education Haryana (HBSE)",
  "Himachal Pradesh-Himachal Pradesh Board of School Education (HPBOSE)",
  "Jharkhand-Jharkhand Academic Council (JAC)",
  "Karnataka-Department of Pre-University Education, Karnataka (PUE)",
  "Kerala-Department of Higher Secondary Education, Kerala (DHSE)",
  "Madhya Pradesh-Board of Secondary Education, Madhya Pradesh (MPBSE)",
  "Maharashtra-Maharashtra State Board of Secondary and Higher Secondary Education (MSBSHSE)",
  "Manipur-Council of Higher Secondary Education, Manipur (COHSEM)",
  "Meghalaya-Meghalaya Board of School Education (MBOSE)",
  "Mizoram-Mizoram Board of School Education (MBSE)",
  "Nagaland-Nagaland Board of School Education (NBSE)",
  "National-Central Board of Secondary Education (CBSE)",
  "National-Council for the Indian School Certificate Examinations (CISCE) - ISC",
  "National-National Institute of Open Schooling (NIOS)",
  "Odisha-Council of Higher Secondary Education, Odisha (CHSE Odisha)",
  "Punjab-Punjab School Education Board (PSEB)",
  "Rajasthan-Board of Secondary Education, Rajasthan (RBSE)",
  "Sikkim-Board of Secondary Education Sikkim",
  "Tamil Nadu-Tamil Nadu Directorate of Government Examinations (TNDGE) - HSC",
  "Telangana-Telangana State Board of Intermediate Education (TSBIE)",
  "Tripura-Tripura Board of Secondary Education (TBSE)",
  "Uttar Pradesh-Board of High School and Intermediate Education Uttar Pradesh (UPMSP)",
  "Uttarakhand-Uttarakhand Board of School Education (UBSE)",
  "West Bengal-West Bengal Council of Higher Secondary Education (WBCHSE)",
  "Other ",
];

export const _12th_Course = [
  "MPC(Mathematics, Physics, Chemistry)",
  "BiPC(Biology, Physics, Chemistry)",
  "MEC(Mathematics, Economics, Commerce)",
  "CEC(Civics, Economics, Commerce)",
  "HEC(History, Economics, Civics)",
  "HPC(History, Political Science, Civics)",
  "MPB(Mathematics, Physics, Biology)",
  "PCMB(Physics, Chemistry, Mathematics, Biology)",
  "CSMB(Computer Science, Mathematics, Biology)",
  "Commerce + CS(Commerce, Accountancy, Computer Science)",
  "DME-Diploma in Mechanical Engineering",
  "DCE-Diploma in Civil Engineering",
  "DEE-Diploma in Electrical Engineering",
  "DECE-Diploma in Electronics & Communication Engg",
  "DCSE-Diploma in Computer Science Engineering",
  "DAIE-Diploma in Automobile Engineering",
  "DIT-Diploma in Information Technology",
  "DMECH-Diploma in Mechatronics",
  "DMIN-Diploma in Mining Engineering",
  "DMLT-Diploma in Medical Lab Technology",
  "DPT-Diploma in Physiotherapy",
  "DRD-Diploma in Radiology Technology",
  "DOT-Diploma in Optometry",
  "DPN-Diploma in Practical Nursing",
  "DPH-Diploma in Pharmacy",
  "DFD-Diploma in Fashion Designing",
  "DID-Diploma in Interior Designing",
  "DAG-Diploma in Animation and Graphics",
  "DWD-Diploma in Web Designing",
  "DBA-Diploma in Business Administration",
  "DOM-Diploma in Office Management",
  "DAF-Diploma in Accounting and Finance",
  "DBF-Diploma in Banking and Finance",
  "DCA-Diploma in Computer Applications",
  "DSE-Diploma in Software Engineering",
  "DHN-Diploma in Hardware and Network",
];

export const Degree_Courses = [
  "B.A. (Bachelor of Arts)-Economics",
  "B.A. (Bachelor of Arts)-English Literature",
  "B.A. (Bachelor of Arts)-Geography",
  "B.A. (Bachelor of Arts)-History",
  "B.A. (Bachelor of Arts)-Languages (Hindi, Sanskrit, French, etc.)",
  "B.A. (Bachelor of Arts)-Philosophy",
  "B.A. (Bachelor of Arts)-Political Science",
  "B.A. (Bachelor of Arts)-Psychology",
  "B.A. (Bachelor of Arts)-Sociology",
  "B.A. in Film Making or Photography",
  "B.Com (Bachelor of Commerce)-Accounting & Finance",
  "B.Com (Bachelor of Commerce)-Banking & Insurance",
  "B.Com (Bachelor of Commerce)-Business Analytics",
  "B.Com (Bachelor of Commerce)-Corporate Secretaryship",
  "B.Com (Bachelor of Commerce)-Taxation",
  "B.Des (Bachelor of Design) -Fashion Design",
  "B.Des (Bachelor of Design) -Graphic Design",
  "B.Des (Bachelor of Design) -Interior Design",
  "B.Des (Bachelor of Design) -Product Design",
  "B.Ed (Bachelor of Education) ",
  "B.El.Ed (Bachelor of Elementary Education) ",
  "B.Pharm (Pharmacy)",
  "B.Sc. (Bachelor of Science)-Biotechnology",
  "B.Sc. (Bachelor of Science)-Botany",
  "B.Sc. (Bachelor of Science)-Chemistry",
  "B.Sc. (Bachelor of Science)-Data Science",
  "B.Sc. (Bachelor of Science)-Environmental Science",
  "B.Sc. (Bachelor of Science)-Forensic Science",
  "B.Sc. (Bachelor of Science)-Mathematics",
  "B.Sc. (Bachelor of Science)-Microbiology",
  "B.Sc. (Bachelor of Science)-Nutrition and Dietetics",
  "B.Sc. (Bachelor of Science)-Physics",
  "B.Sc. (Bachelor of Science)-Zoology",
  "B.Sc. in Data Science & AI",
  "B.Sc. Nursing",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Aerospace",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Artificial Intelligence & Machine Learning",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Biomedical Engineering",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Chemical Engineering",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Civil Engineering",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Computer Science",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Electrical Engineering",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Electronics & Communication",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Mechanical Engineering",
  "B.Tech / B.E. (Bachelor of Technology/Engineering)  -Robotics",
  "B.Tech in Information Technology",
  "BA LL.B. / BBA LL.B. / B.Com LL.B. (Integrated)",
  "Bachelor in Animation & Multimedia",
  "Bachelor of Hotel Management (BHM)",
  "Bachelor of Library and Information Science (BLISc)",
  "Bachelor of Occupational Therapy",
  "Bachelor of Social Work (BSW)",
  "Bachelor of Tourism Studies (BTS)",
  "BAMS (Ayurveda)",
  "BBA (Bachelor of Business Administration)-Entrepreneurship",
  "BBA (Bachelor of Business Administration)-Finance",
  "BBA (Bachelor of Business Administration)-Human Resources",
  "BBA (Bachelor of Business Administration)-International Business",
  "BBA (Bachelor of Business Administration)-Marketing",
  "BCA (Bachelor of Computer Applications)",
  "BDS (Bachelor of Dental Surgery)",
  "BFA (Bachelor of Fine Arts)",
  "BHMS (Homeopathy)",
  "BJMC (Bachelor of Journalism & Mass Communication)",
  "BMM (Bachelor of Mass Media)",
  "BPT (Physiotherapy)",
  "BUMS (Unani)",
  "MBBS (Bachelor of Medicine and Bachelor of Surgery)",
  "Other",
];
