export const educationDegreeOptions = [
  {
    id: "a8490b6d-75a3-49b8-8f14-2016f941110f",
    label: "10th (Secondary School)",
    departments: [],
  },
  {
    id: "854ca904-6b45-44b7-a12b-73890dc802df",
    label: "12th (Higher Secondary)",
    departments: [
      "MPC (Maths, Physics, Chemistry)",
      "BiPC (Biology, Physics, Chemistry)",
      "CEC (Civics, Economics, Commerce)",
      "MEC (Maths, Economics, Commerce)",
      "HEC (History, Economics, Civics)",
      "Vocational Courses",
      "Arts",
      "Commerce",
      "Science",
    ],
  },
  {
    id: "fe645b54-d198-4f32-aa0d-c85437189a59",
    label: "Diploma (Polytechnic)",
    departments: [
      "Computer Engineering",
      "Civil Engineering",
      "Electrical Engineering",
      "Mechanical Engineering",
      "Electronics Engineering",
    ],
  },
  {
    id: "5ed780c2-8123-4f18-b60a-f04bb9cbc610",
    label: "ITI (Industrial Training Institute)",
    departments: [
      "Electrician",
      "Fitter",
      "Welder",
      "Mechanic (Motor Vehicle)",
      "Machinist",
      "Turner",
      "Plumber",
      "Carpenter",
      "Refrigeration and Air Conditioning",
      "Electronics Mechanic",
      "Diesel Mechanic",
      "Tool & Die Maker",
      "Computer Operator and Programming Assistant (COPA)",
      "Draughtsman (Civil)",
      "Draughtsman (Mechanical)",
      "Information Technology",
      "Automobile",
      "Wireman",
    ],
  },
  {
    id: "19dfe339-a54d-428b-9d11-3451355fe060",
    label: "Bachelor of Arts (BA)",
    departments: [
      "History",
      "Political Science",
      "Psychology",
      "Sociology",
      "Philosophy",
      "Literature",
      "Languages",
    ],
  },
  {
    id: "06f10bbb-e2bb-4379-9fc4-3502550ec8cf",
    label: "Bachelor of Science (BSc)",
    departments: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biology",
      "Computer Science",
      "Environmental Science",
      "Zoology",
      "Botany",
    ],
  },
  {
    id: "f7d03b97-5954-44a8-83ef-259c9aa4e44b",
    label: "Bachelor of Commerce (BCom)",
    departments: ["Accounting", "Finance", "Economics", "Banking", "Taxation"],
  },
  {
    id: "55193bda-adae-4367-8a44-c73c778f7ff7",
    label: "Bachelor of Business Administration (BBA)",
    departments: [],
  },
  {
    id: "4a567519-22db-4525-9750-438e3e5a3b3e",
    label: "Bachelor of Computer Applications (BCA)",
    departments: [],
  },
  {
    id: "cb13f881-ef86-40de-a0be-c28548ba95b5",
    label: "Bachelor of Education (B.Ed)",
    departments: [],
  },
  {
    id: "5069b279-2490-42a2-89fa-8170a3c1c5b5",
    label: "Bachelor of Engineering (BE)",
    departments: [
      "Computer Engineering",
      "Electronics",
      "Electrical",
      "Mechanical",
      "Civil",
      "Instrumentation",
      "Biomedical",
    ],
  },
  {
    id: "76f9d8dc-0b5f-46d5-91da-e1e8b32fb16b",
    label: "Bachelor of Technology (BTech)",
    departments: [
      "Computer Science",
      "Information Technology",
      "Electronics and Communication",
      "Electrical",
      "Mechanical",
      "Civil",
      "Artificial Intelligence",
      "Data Science",
      "Mechatronics",
    ],
  },
  {
    id: "52f7804a-a3f7-4e16-9731-637bd04db7bf",
    label: "Bachelor of Fine Arts (BFA)",
    departments: [],
  },
  {
    id: "246387ec-5562-452f-a2fa-fd5da107fc41",
    label: "Bachelor of Pharmacy (B.Pharm)",
    departments: [
      "Pharmaceutical Chemistry",
      "Pharmacology",
      "Pharmaceutics",
      "Pharmacognosy",
    ],
  },
  {
    id: "df745a94-fd37-42bd-a05b-a0c63cb794c7",
    label: "Bachelor of Dental Surgery (BDS)",
    departments: [],
  },
  {
    id: "ed5663f1-6b8d-4b0d-b7d0-00350f39e0f8",
    label: "Bachelor of Law (LLB)",
    departments: [],
  },
  {
    id: "21f02adc-0664-4e50-b742-78a8e4e4a3c8",
    label: "MBBS (Medical)",
    departments: [],
  },
  {
    id: "d8ef1755-03e4-463e-a18a-2de1c3fc1ada",
    label: "Master of Arts (MA)",
    departments: [
      "History",
      "Political Science",
      "Psychology",
      "Philosophy",
      "Sociology",
      "English",
      "Linguistics",
    ],
  },
  {
    id: "61ba26e8-04f1-45aa-b4c1-0f68ea0db9a1",
    label: "Master of Science (MSc)",
    departments: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Botany",
      "Zoology",
      "Biotechnology",
      "Environmental Science",
      "Data Analytics",
    ],
  },
  {
    id: "77c5312e-9fde-48ee-bdb9-f7610543ad06",
    label: "Master of Commerce (MCom)",
    departments: [
      "Accounting",
      "Finance",
      "Economics",
      "Taxation",
      "Business Studies",
    ],
  },
  {
    id: "1d8d395f-fc01-45d6-b496-ed9543eb3568",
    label: "Master of Business Administration (MBA)",
    departments: [
      "Marketing",
      "Finance",
      "Human Resources",
      "Operations",
      "IT",
      "Business Analytics",
      "International Business",
    ],
  },
  {
    id: "2f54432f-eb2b-4f0d-a6d6-3e3a46c12f7e",
    label: "Master of Computer Applications (MCA)",
    departments: [
      "Software Development",
      "Cybersecurity",
      "AI",
      "Web Technologies",
      "Data Science",
    ],
  },
  {
    id: "c0b502bc-efb0-4fb4-9376-603782037314",
    label: "Master of Engineering (ME)",
    departments: [
      "Mechanical",
      "Electrical",
      "Civil",
      "Computer",
      "Electronics",
      "Instrumentation",
    ],
  },
  {
    id: "0263be24-85f8-4b5d-8f17-24bb22a167cd",
    label: "Master of Technology (MTech)",
    departments: [
      "Computer Science",
      "Information Technology",
      "Electrical",
      "Mechanical",
      "Electronics",
      "AI & ML",
      "Data Science",
    ],
  },
  {
    id: "3da423a6-9256-4e11-bb0b-a3faaaf06411",
    label: "Master of Education (M.Ed)",
    departments: [],
  },
  {
    id: "f2cf226c-be1f-4fe3-b91e-c78cfe02109a",
    label: "Master of Fine Arts (MFA)",
    departments: [],
  },
  {
    id: "d5c43584-af65-41ee-bfdc-033c772ffa70",
    label: "Master of Laws (LLM)",
    departments: [],
  },
  {
    id: "5969533f-a8b0-4151-b068-de27c46c73cd",
    label: "Master of Pharmacy (M.Pharm)",
    departments: [
      "Pharmaceutical Analysis",
      "Pharmacology",
      "Pharmaceutics",
      "Pharmaceutical Chemistry",
    ],
  },
  {
    id: "b362fa03-6f80-483f-ad95-10b9fa929c75",
    label: "Doctor of Philosophy (PhD)",
    departments: [],
  },
  {
    id: "ce78a075-3edc-4d70-b2df-30c6480c0cab",
    label: "Doctor of Science (DSc)",
    departments: [],
  },
  {
    id: "60840f3b-15cd-4941-8ae7-81365fc245b2",
    label: "Chartered Accountant (CA)",
    departments: [],
  },
  {
    id: "d4592977-f7fd-4e9d-9541-a1961854d6e0",
    label: "Company Secretary (CS)",
    departments: [],
  },
  {
    id: "199dd9b2-17d7-4c09-8cb1-92ecf41c1c87",
    label: "Cost and Management Accountant (CMA)",
    departments: [],
  },
];
export default educationDegreeOptions;
